Refresh jazzy documentation
IBM-Swift/Kitura-Markdown pull request #16
Opened 2018-06-07 12:25 UTC by djones6

2018-06-07 13:26 UTC, helenmasters requested changes
I think it would be good to make a few improvements to the jazzy doc whilst we're in here!

The description is currently "An implementation of Kitura’s TemplateEngine protocol. In particular this templating engine takes files in Markdown (.md) format and converts them to HTML. In addition this class has some helper methods for taking Markdown formatted text and converting it to HTML.

I think it'd be much clearer to make it something like "An implementation of Kitura’s TemplateEngine protocol that enables a Kitura server to serve HTML content generated from Markdown templates (`.md` files). This class also has some helper methods that take Markdown formatted text from a Data struct, or String and convert it to HTML."

2018-06-07 13:33 UTC, helenmasters commented
fileExtension - The file extension of files in the views directory that will be rendered by a particular templating engine.

I think this should be "The file extension of files that will be rendered by the KituraMarkdown template engine." Perhaps we should also add "By default Kitura will search for these in the  ./Views/ directory, you can customize this by setting the `router.viewsPath` property."

2018-06-07 13:34 UTC, helenmasters commented
Within init() - Create a KituraMarkdown instance needs a full stop on the end.

2018-06-07 13:35 UTC, helenmasters commented
There is a parameter called `options` which appears in a couple of places which needs a sentence next to it rather than "markdown options".

2018-06-07 13:37 UTC, helenmasters commented
Every `from` parameter (there are 3 references to this parameter) needs a full stop at the end of the associated description.

2018-06-07 13:38 UTC, helenmasters commented
The `pageTemplate` parameter has the description "The HTML page template used" which needs a full stop at the end.

2018-06-07 13:39 UTC, helenmasters commented
There is no difference in the descriptions for:
`public static func render(from: String) -> String` and `public static func render(from: String, pageTemplate: String) -> String` I'd like there to be a difference as otherwise why are we passing in pageTemplate?

2018-06-07 13:42 UTC, helenmasters commented
The API doc for the struct `MarkdownOptions` could do with some descriptions adding and full stops at the end of sentences and parameter descriptions.

2018-06-07 13:49 UTC, helenmasters commented
It would be good to add at least one usage example, there is one in the github README for this repo if required.

2018-06-12 16:12 UTC, djones6 commented
I've addressed some of the review comments.  Still need:
- usage example
- some kind of example of how the HTML page template should be overridden (the sole purpose of `MarkdownOptions`).  This doesn't seem to be covered in any of our guides so I have inferred its usage from the code.

2018-06-28 14:43 UTC, djones6 commented
@helenmasters Review comments addressed.  And I've also (hopefully) solved the jazzy-doc mergeability issue.

2018-07-03 09:52 UTC, helenmasters commented on Sources/KituraMarkdown/KituraMarkdown.swift
> + let markdownOptions = MarkdownOptions(pageTemplate: "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"></head><body><div><snippetInsertLocation></snippetInsertLocation></div></body></ht
If you remove the extra ')' at the end of this line the PR looks good to go.

2018-07-03 10:45 UTC, helenmasters approved these changes

2018-07-03 15:32 UTC, merged